apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workload
  name: workload
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload
  strategy: {}
  template:
    metadata:
      labels:
        app: workload
    spec:
      containers:
      - image: rqtx/workload:server
        name: workload
        env:
        - name: ADDR
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
        - name: FIBO
          value: "35"
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "100m"
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: workload
  name: workload
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workload
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workload
  name: workload
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: workload
