kind: PersistentVolume
apiVersion: v1
metadata:
  name: config-volume-pv
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./volume"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: zigbee2mqtt-data
spec:
  storageClassName: generic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
