---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: kingdevnl/whoami:arm
        ports: 
        - containerPort: 80
        resources:
          limits:
            memory: "4Mi"
            cpu: "1m"
          requests:
            memory: "4Mi"
            cpu: "1m"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: model
                operator: In
                values:
                - rpi3
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - whoami
              topologyKey: "kubernetes.io/hostname"