---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: kingdevnl/whoami:arm
        ports: 
        - containerPort: 80
        resources:
          limits:
            memory: "4Mi"
            cpu: "1m"
          requests:
            memory: "4Mi"
            cpu: "1m"
